services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 5s
      timeout: 2s
      retries: 10

  web:
    build: .
    container_name: web
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: cooking-recipes.py
      SECRET_KEY: your-secret-key
      ADMIN_PASSWORD: your-admin-password
      S3_ENDPOINT_URL: http://minio:9000
      S3_ACCESS_KEY: minioadmin
      S3_SECRET_KEY: minioadmin
      S3_BUCKET_NAME: recipes
      S3_REGION: us-east-1
      S3_SECURE: "False"
      S3_PUBLIC_URL: http://localhost:9000
    depends_on:
      minio:
        condition: service_healthy
    volumes:
      - .:/app

volumes:
  minio-data:
